JobTrack/Models/Job.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace JobTrack.Models
{
    public class Job
    {

        [Key]
        public int JobId { get; set; }

        [Required]
        public string Position { get; set; }

        [DataType(DataType.Date)]
        public DateTime? DateApplied{ get; set; }

        [Required]
        public int StatusId { get; set; }

        public Status Status { get; set; }

      
        public string ApplicationUserId { get; set; }

        public ApplicationUser ApplicationUser { get; set; }

        [Required]
        public int CompanyId { get; set; }

        public Company Company { get; set; }

    }
}

JobTrack/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JobTrack.Data;
using JobTrack.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using JobTrack.Models;

namespace JobTrack.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        //Injecting Application DBContext and defining the userManager ApplicationUser.
        public CompaniesController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
    private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

    // GET: Companies
    [Authorize]
    public async Task<IActionResult> Index()
        {
            return View(await _context.Company.ToListAsync());
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company
                .FirstOrDefaultAsync(m => m.CompanyId == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // GET: Companies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CompanyId,Name,Location")] Company company)
        {
            ModelState.Remove("Contacts");
            if (ModelState.IsValid)
            {
                _context.Add(company);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(company);
        }

        // GET: Companies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company.FindAsync(id);
            if (company == null)
            {
                return NotFound();
            }

            CompanyEditViewModel CompanyEditViewModel = new CompanyEditViewModel();
            CompanyEditViewModel.Company = company;
            return View(CompanyEditViewModel);


            //return View(company);
        }

        // POST: Companies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CompanyId,Name,Location")] Company company)
        {
            var user = await GetCurrentUserAsync();

            //Company.ApplicationUser = user;
            //_context.Update(company);
            //await _context.SaveChangesAsync();


            if (id != company.CompanyId)
            {
                return NotFound();
            }
            ModelState.Remove("company.Contacts");
            ModelState.Remove("company.Jobs");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(company);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CompanyExists(company.CompanyId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            CompanyEditViewModel CompanyEditViewModel = new CompanyEditViewModel();
            CompanyEditViewModel.Company = company;
            return View(CompanyEditViewModel);
           
        }

        // GET: Companies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var company = await _context.Company
                .FirstOrDefaultAsync(m => m.CompanyId == id);
            if (company == null)
            {
                return NotFound();
            }

            return View(company);
        }

        // POST: Companies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var company = await _context.Company.FindAsync(id);
            _context.Company.Remove(company);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CompanyExists(int id)
        {
            return _context.Company.Any(e => e.CompanyId == id);
        }
    }
}

JobTrack/Controllers/JobsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using JobTrack.Data;
using JobTrack.ViewModels;
using JobTrack.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace JobTrack.Controllers
{
    public class JobsController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ApplicationDbContext _context;

        public JobsController(ApplicationDbContext context,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        // Stores private reference to Identity Framework user manager
        



        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);
        // GET: Jobs
        [Authorize]
        public async Task<IActionResult> Index()
        {
            var user = await GetCurrentUserAsync();
            var applicationDbContext = _context.Job.Include(j => j.ApplicationUser).Include(j => j.Company).Include(j => j.Status).Where(j => j.ApplicationUserId == user.Id);
            return View(await applicationDbContext.ToListAsync());

           

        }

        // GET: Jobs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .Include(j => j.ApplicationUser)
                .Include(j => j.Company)
                .Include(j => j.Status)
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }

            JobDetailsViewModel JobDetails = new JobDetailsViewModel();
            JobDetails.Job = job;
            return View(JobDetails);
        }

        // GET: Jobs/Create
        public IActionResult Create()
        {
            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "Id");

            //ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Location");

            JobCreateViewModel JobCreateViewModel = new JobCreateViewModel(_context);
            return View(JobCreateViewModel);

            //ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Name");
            //return View();
        }

        // POST: Jobs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("JobId,Name,Position,DateApplied,StatusId,CompanyId")] Job job)
        {
            ModelState.Remove("ApplicationUserId");
            if (ModelState.IsValid)
            {
                var user = await GetCurrentUserAsync();
               
                job.ApplicationUser= user;
                _context.Add(job);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", job.ApplicationUserId);
            ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Location", job.CompanyId);
            ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Name", job.StatusId);

            JobCreateViewModel JobCreateViewModel = new JobCreateViewModel(_context);
            return View(JobCreateViewModel);
            
        }

        // GET: Jobs/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var Job = await _context.Job.FindAsync(id);
            if (Job == null)
            {
                return NotFound();
            }
            //ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", Job.ApplicationUserId);

            JobEditViewModel JobEditViewModel = new JobEditViewModel(_context);
            JobEditViewModel.Job = Job;
            return View(JobEditViewModel);

            //ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Location", job.CompanyId);
            //ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Name", job.StatusId);
            //return View(JobCreateViewModel);
        }

        // POST: Jobs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("JobId,Name,Position,DateApplied,StatusId,ApplicationUserId,CompanyId")] Job job)
        {
           
            var user = await GetCurrentUserAsync();

            job.ApplicationUser = user;
            _context.Update(job);
            await _context.SaveChangesAsync();


            if (id != job.JobId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JobExists(job.JobId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            //JobEditViewModel JobEditViewModel = new JobEditViewModel(_context);
            //return base.View(JobEditViewModel);

            //ViewData["ApplicationUserId"] = new SelectList(_context.ApplicationUser, "Id", "Id", job.ApplicationUserId);
            //ViewData["CompanyId"] = new SelectList(_context.Company, "CompanyId", "Location", job.CompanyId);
            //ViewData["StatusId"] = new SelectList(_context.Status, "StatusId", "Name", job.StatusId);
            return View(job);
        }

        // GET: Jobs/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job = await _context.Job
                .Include(j => j.ApplicationUser)
                .Include(j => j.Company)
                .Include(j => j.Status)
                .FirstOrDefaultAsync(m => m.JobId == id);
            if (job == null)
            {
                return NotFound();
            }

            return View(job);
        }

        // POST: Jobs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var job = await _context.Job.FindAsync(id);
            _context.Job.Remove(job);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JobExists(int id)
        {
            return _context.Job.Any(e => e.JobId == id);
        }
    }
}

JobTrack/Views/Jobs/Create.cshtml
@model JobTrack.ViewModels.JobCreateViewModel


@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Job.CompanyId" class="control-label">Company Name</label>
                <select asp-for="Job.CompanyId" class="form-control" asp-items="@Model.Company"></select>
            </div>
            @*<div class="form-group">
                <label asp-for="Job.Name" class="control-label"></label>
                <input asp-for="Job.Name" class="form-control" />
                <span asp-validation-for="Job.Name" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Job.Position" class="control-label">Position</label>
                <input asp-for="Job.Position" class="form-control" />
                <span asp-validation-for="Job.Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.DateApplied" class="control-label">Date Applied</label>
                <input asp-for="Job.DateApplied" class="form-control" />
                <span asp-validation-for="Job.DateApplied" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.StatusId" class="control-label">Current Status</label>
                <select asp-for="Job.StatusId" class="form-control" asp-items="@Model.Status"></select>
            </div>
           
            @*<div class="form-group">
            <label asp-for="Job.ApplicationUserId" class="control-label"></label>
            <select asp-for="Job.ApplicationUserId" class ="form-control" asp-items="ViewBag.ApplicationUserId"></select>
        </div>*@

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
                

            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a> |
    <a asp-controller="Companies" asp-action="Create">Add Company</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JobTrack/Views/Jobs/Delete.cshtml
@model JobTrack.Models.Job

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateApplied)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateApplied)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ApplicationUser)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ApplicationUser.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Company)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Company.Location)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="JobId" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

JobTrack/Views/Jobs/Details.cshtml
@model JobTrack.ViewModels.JobDetailsViewModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Job</h4>
    <hr />
    <dl class="dl-horizontal">
        @*<dt>
            @Html.DisplayNameFor(model => model.Job.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.Name)
        </dd>*@
        <dt>
            @Html.DisplayNameFor(model => model.Job.Position)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.Position)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Job.DateApplied)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.DateApplied)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Job.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.Status.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Job.ApplicationUser)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.ApplicationUser.Id)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Job.Company)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Job.Company.Location)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Job.JobId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

JobTrack/Views/Jobs/Edit.cshtml
@model JobTrack.ViewModels.JobEditViewModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>   

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Job.JobId" />
           
            <div class="form-group">
                <label asp-for="Job.Position" class="control-label"></label>
                <input asp-for="Job.Position" class="form-control" />
                <span asp-validation-for="Job.Position" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.DateApplied" class="control-label"></label>
                <input asp-for="Job.DateApplied" class="form-control" />
                <span asp-validation-for="Job.DateApplied" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.StatusId" class="control-label"></label>
                <select asp-for="Job.StatusId" class="form-control" asp-items="@Model.Status"></select>
                <span asp-validation-for="Job.StatusId" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Job.ApplicationUserId" class="control-label"></label>
                <select asp-for="Job.ApplicationUserId" class="form-control" asp-items="@Model.ApplicationUser"></select>
                <span asp-validation-for="Job.ApplicationUserId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Job.CompanyId" class="control-label"></label>
                <select asp-for="Job.CompanyId" class="form-control" asp-items="@Model.Company"></select>
                <span asp-validation-for="Job.CompanyId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

JobTrack/Views/Jobs/Index.cshtml
@model IEnumerable<JobTrack.Models.Job>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            @*<th>
                @Html.DisplayNameFor(model => model.Name)
            </th>*@
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateApplied)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApplicationUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Company)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            @*<td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>*@
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateApplied)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApplicationUser.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Company.Name)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.JobId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.JobId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.JobId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>